package:
  name: accelerate
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed') }}

source:
  git_url: git@github.com:sklam/conda_build_tag_bug.git
  # git_url: https://github.com/sklam/conda_build_tag_bug.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
  run:
    - python
